### ISSUE TITLE
Database Crash with rel::PgRelation::with_lock

### ISSUE THREAD

**Issue by JohnHVancouver** [tcdi/plrust#107]
In PL/Rust if you create a function like so and execute it:

```
 CREATE OR REPLACE FUNCTION test_open_rel() RETURNS text
    IMMUTABLE STRICT
    LANGUAGE PLRUST AS
$$
[dependencies]
    # Add Cargo.toml dependencies here.

[code]
    use pgx::*;
    let rel = rel::PgRelation::with_lock(1259, 0);

    Some("foo".to_string())
$$;
```

it'll crash the database when assertions are enabled. Here's the logs from engine:

```
2022-11-03 08:55:30.605 UTC [17140] LOG:  database system is ready to accept connections
TRAP: FailedAssertion("lockmode != NoLock || IsBootstrapProcessingMode() || CheckRelationLockedByMe(r, AccessShareLock, true)", File: "re
lation.c", Line: 70, PID: 17154)
postgres: hsuchen plrust 127.0.0.1(58986) SELECT(ExceptionalCondition+0x90)[0x907e90]
postgres: hsuchen plrust 127.0.0.1(58986) SELECT(relation_open+0xa7)[0x4a2327]
```

Presumably it's failing the `lockmode != NoLock` portion.

https://github.com/postgres/postgres/blob/2d0bbedda7c4fbf7092c39b0c06b56cb238e15d7/src/backend/access/common/relation.c#L68-L70

The quick fix would be to cfg[plrust] and check for lockmode == 0 but I'm not sure if that's the right thing to do. I wonder if there's a use case in PL/Rust to attempt to lock something, and come back to re-lock it again with NoLock? I suppose if you're calling things in one transaction across multiple functions and you might've locked it earlier?

**Comment by workingjubilee** [comment]
Initial vibe this is giving me suggests a more fundamental bug in PgRelation's assumptions and design may exist? Bringing down the database may not be "unsafe" strictly speaking but this behavior doesn't seem like something we usually want out of safe APIs. It's... low quality of implementation.

**Comment by JohnHVancouver** [comment]
I'm not familiar with how originally the "safety-ness" of something is determined. Letting the database crash is.. well undesirable, especially in the context of PL/Rust if it were to be trusted. 

It seems tricky? Unless you really look into the source code of what we're calling out to and testing it you wouldn't really know which assertions are being tripped.

Maybe in this case we can just add a call to `CheckRelationLockedByMe` ? I don't see it in pgx_pg_sys though, not sure how those bindings are generated

**Comment by workingjubilee** [comment]
A fundamental principle around Rust safety is that all inputs should still yield _sound_ behavior, and that is a hard limit. The type system is then used to constrain the inputs to those that would be valid, in order to expose safe functions.

This also implies, extensionally, in a softer way, that Rust code should be "well behaved" under all inputs, or specifically explain clauses like "will `panic!` if so and so" or "can deadlock maybe?" 

Which means a naked call to
```c

/* ----------------
 *		relation_open - open any relation by relation OID
 *
 *		If lockmode is not "NoLock", the specified kind of lock is
 *		obtained on the relation.  (Generally, NoLock should only be
 *		used if the caller knows it has some appropriate lock on the
 *		relation already.)
 *
 *		An error is raised if the relation does not exist.
 *
 *		NB: a "relation" is anything with a pg_class entry.  The caller is
 *		expected to check whether the relkind is something it can handle.
 * ----------------
 */
```
a function that says "the caller is expected to check..." is not acceptable.

**Comment by workingjubilee** [comment]
@JohnHVancouver I have opened tcdi/pgx#886 to address this by making this function `unsafe`. I believe the design of PgRelation's API here would have to be substantially revisited to make a safe version.
