### ISSUE TITLE
Reexamine everything around Drop as of PgTryBuilder

### ISSUE THREAD

**Issue by workingjubilee** [tcdi/plrust#110]
https://github.com/tcdi/pgx/pull/834 has landed and completely blows up previous assumptions regarding how PL/Rust has to work with respect to PGX (but in a good way, mostly???). But it means everything in postgrestd and PL/Rust has to reevaluate in light of this new information.

**Comment by eeeebbbbrrrr** [comment]
We decided that `pallocator` is no longer necessary.  Is there anything else we should be concerned about?

**Comment by eeeebbbbrrrr** [comment]
I don't believe there is.  Closing.
