### ISSUE TITLE
Parameters don't line up with the names properly

### ISSUE THREAD

**Issue by jim-mlodgenski** [tcdi/plrust#111]
When 2 of the same data type are passed in, the names don't match the ordinal number correctly.  

```
CREATE OR REPLACE FUNCTION test(a int, b int) 
  RETURNS int AS 
$$
  Some(a.unwrap())
$$ LANGUAGE plrust;

=# select test(1, 2);
 test 
------
    2
(1 row)

```

**Comment by eeeebbbbrrrr** [comment]
Woah.

Thanks for the report.

**Comment by workingjubilee** [comment]
fwiw this test would be written the same as
```sql
CREATE OR REPLACE FUNCTION test(a int, b int) 
  RETURNS int AS 
$$
  a
$$ LANGUAGE plrust;
```

I have reproduced the error as a test and while my initial hypothesis was a problem in pgx, it seems to be unique to PL/Rust and the equivalent test in pgx passes fine.

**Comment by workingjubilee** [comment]
...This appears to be a "Heisenbug", which may explain why we have not seen it before. That is, it does not seem to happen consistently, and the ordering that happens somehow can change when the functions are rebuilt and retested. It also seems to be exacerbated by simultaneously submitting multiple PL/Rust functions at once, but is not exclusive to that.

**Comment by workingjubilee** [comment]
Ah. The lesson here is to never use `HashMap` (which is, by default, `HashMap<K, V, RandomState>`... i.e. the data is hashed with a random state seed selected upon creation of the `HashMap`) and expect a deterministic ordering.
