### ISSUE TITLE
Recompile function automatically if function .so file is not found

### ISSUE THREAD

**Issue by anth0nyleung** [tcdi/plrust#113]
In cases where the .so file is not found, such as cases where the .so file is only created on writer but not on replica, or cases where the machines somehow switches to use a CPU on another architecture (e.g. x86 -> aarch64, vice versa). We'd need to use `plrust.recompile_function` to recompile all the existing functins. 

We can introduce a boolean guc which controls whether plrust would recompile a function if it found that the .so file is missing.

**Comment by eeeebbbbrrrr** [comment]
The function will no longer "not be found" because we store it in the database now.
