### ISSUE TITLE
Arbitrary Shell Execution through #[link_section]

### ISSUE THREAD

**Issue by JohnHVancouver** [tcdi/plrust#118]
The shell code in init_array is always executed first leading to arbitrary shell execution potentially.

-- Repro removed temporarily 

Is there something in Cargo/rustc or a more "Rust" way to detect and prevent these things?

**Comment by workingjubilee** [comment]
These kinds of things can be filtered via this flotilla of lints: https://github.com/rust-lang/rust/issues/82499

**Comment by workingjubilee** [comment]
> The naive solution might be to just scan for #[ and error during parsing the code, but I'm not familiar with how Rust interprets Attributes, it seems something like works as well.

To address this part of your question more directly: Rust is very, very lax about whitespace in most cases where a logical segment in the parse could be interpreted as existing.

**Comment by jbrindle** [comment]
What lints can we add to Cargo.toml to validate that they will actually catch this behavior?

**Comment by workingjubilee** [comment]
It involves restructuring the build a bit to let us do a "dry run" pre-build and then do it "for real", as mentioned. I am working on that PR.

**Comment by workingjubilee** [comment]
I have a draft branch for this that successfully catches this specific example, but it is still technically possible to get `#[link_section]` without `#[no_mangle]` by, unless using a higher rustc version than 1.61.0, so I will polish it up and submit it next week but it will contain an ignored test unless we also have consensus on raising MSRV.

**Comment by workingjubilee** [comment]
TODO:
- [x] Test for `#[no_mangle]`
  - [x] ...passes
  - [ ] ...on main
- [x] Test for `#[link_section]`
  - [x] ...passes
  - [ ] ...on main
- [ ] Create tests for other "unsafe attributes"
- [ ] Make other unsafe attribute tests pass
- [ ] Make other unsafe attribute tests pass on main
