### ISSUE TITLE
Discuss:  Use `pg_proc.prosrc` field or current `plrust.plrust_proc` table?

### ISSUE THREAD

**Issue by eeeebbbbrrrr** [tcdi/plrust#126]
After some discussions with @JohnHVancouver, I'm not sure if we should continue down the path of using our new `plrust.plrust_proc` table for storing shared objects or if we should hijack the `prosrc` column from the `pg_proc` system catalog?

# Pros/Cons of `pg_proc.prosrc`

## Pros

- No need to manage permissions
- Doesn't interfere with backups/restores
- It's always there

## Cons

- Must store "function.so" as base64
- Limited to 1G of text
- a complex, say json-based, format for our data destroys the output of psql's `\sf` command
- Must hook ALTER FUNCTION SET STRICT

# Pros/Cons of our own `plrust.plrust_proc` table

## Pros

- Most of the work is already done!
- We have more control now and in the future (this is probably worth 3 pros)

## Cons

- Must hook ALTER FUNCTION SET [SCHEMA, STRICT], ALTER FUNCTION RENAME TO, ALTER SCHEMA RENAME, DROP FUNCTION, DROP SCHEMA
- Permission handling is unclear as currently plrust uses SPI to INSERT/UPDATE/DELETE the table

I'm not sure what the right answer is.  When I write this out, it's kinda clear we ought to continue with our own table.  So if that's the answer, how do we handle mutating the table such that plrust can do what it needs but a regular user from SQL can't?

**Comment by JohnHVancouver** [comment]
> Limited to 1G of text

I don't think I'm familiar with this limitation? Ah is it the field size limitation? I'm not familiar with how TOAST works here (if it does at all)

> We have more control now and in the future (this is probably worth 3 pros)

Fair. I suppose if you go with prosrc and you want to add any additional columns, you're really limited in continuing to put things into prosrc. If at which point you decide to have a table in the future might as well have gone with it

> how do we handle mutating the table such that plrust can do what it needs but a regular user from SQL can't

I guess we have to go with HeapTuple manipulations? Which sounds annoying but that would allow the proc_utility hooks that are currently there to be built off of

**Comment by eeeebbbbrrrr** [comment]
> > Limited to 1G of text
> 
> I don't think I'm familiar with this limitation? Ah is it the field size limitation? I'm not familiar with how TOAST works here (if it does at all)

From [here](https://www.postgresql.org/docs/current/datatype-character.html):  "In any case, the longest possible character string that can be stored is about 1 GB"

I think columns in system tables are toastable?  I'm having difficulty confirming that tho.

Regardless, yeah, I think using our own table is the answer.  I'm going to finish the various hooks, all using SPI, then I'll loop back around and deal with it directly via HeapTuple apis.

**Comment by eeeebbbbrrrr** [comment]
We've decided to use `pg_catalog.pg_proc.prosrc` and this has been implemented for awhile now.
