### ISSUE TITLE
Test for other "unsafe attributes"

### ISSUE THREAD

**Issue by workingjubilee** [tcdi/plrust#132]
Some attributes are implicitly `unsafe`, without containing the `unsafe` token in Rust. I will refer to these as "unsafe attributes". We probably need to replicate the work in https://github.com/tcdi/plrust/pull/128 to make sure we detect these.

- Create tests for successfully denying all "unsafe attributes"
  - [x] `#[no_mangle]` https://github.com/tcdi/plrust/pull/128
  - [x] `#[link_section]` https://github.com/tcdi/plrust/pull/128
  - [x] `#[export_name]` https://github.com/tcdi/plrust/pull/177
  - [ ] `#[link]` maybe?
- Make all unsafe attribute tests pass
  - [x] `#[no_mangle]` https://github.com/tcdi/plrust/pull/128
  - [x] `#[link_section]` https://github.com/tcdi/plrust/pull/131
  - [x] `#[export_name]` https://github.com/tcdi/plrust/pull/177
  - [ ] `#[link]` maybe?

**Comment by thomcc** [comment]
`#[link]` is definitely something we need to forbid, but thankfully plrustc's lint against `extern` blocks does so. Closing as completed.
