### ISSUE TITLE
Support non immutable functions?

### ISSUE THREAD

**Issue by jaredramirez** [tcdi/plrust#14]
Hey there,

This is really cool! All the examples I see in `lib.rs` are immutable functions. Is there any support for selecting/inserting/updating rows?

**Comment by eeeebbbbrrrr** [comment]
I'm not sure I completely understand your question.  With pl/rust, you're the one that writes the `CREATE FUNCTION` statement, so you get to decide if that function is immutable or volatile (the default, if unspecified).  

Can you be a little more specific?

**Comment by jaredramirez** [comment]
Hey there, sorry for the unclear question. My actual question is: With `plrust` can you select/modify/update/delete rows? For example, in `plv8`, you can do things like:
```
var plan = plv8.prepare( 'SELECT * FROM tbl WHERE col = $1', ['int'] );
var rows = plan.execute( [1] );
...
```
Is there an similar thing in `plrust`?

**Comment by Hoverbear** [comment]
I've now tested and it does work. See #22 for the example.
