### ISSUE TITLE
Writing .so from table to disk to execute it

### ISSUE THREAD

**Issue by JohnHVancouver** [tcdi/plrust#149]
Currently when we read the .so from the table, we write a temporary file in the work_dir 
https://github.com/tcdi/plrust/blob/main/plrust/src/plrust_proc.rs#L81-L82

and then use Library::new to instantiate the library and get symbols from it.

https://github.com/tcdi/plrust/blob/main/plrust/src/user_crate/ready.rs#L33-L34

It seems unnecessary to re-write it into disk, wondering if something like mmap with dlopen would work better here

**Comment by eeeebbbbrrrr** [comment]
This was resolved in 070b1
