### ISSUE TITLE
`target_postgres` and cross compilation

### ISSUE THREAD

**Issue by thomcc** [tcdi/plrust#156]
`target_postgrestd` causes some problems for cross compilation, because we use `{x86_64,aarch64}-unknown-linux-postgres` for target triples when std is postgrestd.

We should find a way to work around this in a satisfying and non-hacky way, but as a stop gap, when under `target_postgrestd`, we should set the following environment vars:

1. Set `CARGO_TARGET_{arch.to_uppercase()}_UNKNOWN_LINUX_POSTGRES_LINKER` to whatever value we would set `CARGO_TARGET_{arch.to_uppercase()}_UNKNOWN_LINUX_GNU_LINKER` linker to if `target_postgrestd were inactive.

	For example `CARGO_TARGET_AARCH64_UNKNOWN_LINUX_POSTGRES_LINKER=aarch64-linux-gnu-gcc`.

2. Set `BINDGEN_EXTRA_CLANG_ARGS_{rust_postgrestd_target}` to `-target {real_rust_target} -ccc-gcc-name {target_linker} -isystem {target_header_location}`, where for now we can just use `/usr/{real_target_without_unknown}/include` for the `target_header_location`. For example

	```rs
	let real_rust_target = "aarch64-unknown-linux-gnu";
	let postgrestd_target = real_target.replace("gnu", "postgres"); // `aarch64-unknown-linux-postgres`
	let toolchain_prefix = real_target.replace("-unknown", ""); // `aarch64-linux-gnu`
	let linker = format!("{toolchain_prefix}-gcc"); // `aarch64-linux-gnu-gcc`
	let header_location = format!("/usr/{toolchain_prefix}/include");
	// You'd probably attach this to the Command in reality.
	let env_to_set: &[(String, String)] = &[
	    (
	        format!("CARGO_TARGET_{}_LINKER", postgrestd_target.to_uppercase().replace('-', "_")),
	        linker.clone(),
	    ),
	    (
	        format!("BINDGEN_EXTRA_CLANG_ARGS_{}", postgrestd_target),
	        format!("-target {real_rust_target} -ccc-gcc-name {linker} -isystem {header_location}"),
	    ),
	];
	```
This is not very robust and is extremely specific to how e.g. Debian's cross-compile toolchains are set up, but it gets the point across (and allows anybody who takes the time to set one up in the same manner to have things work).

**Comment by eeeebbbbrrrr** [comment]
Just making some notes...

To install a "aarch64" version of `postgrestd` on an otherwise correctly-configured-for-cross-compilation x86_64 machine:

```shell
$ cd plrust/postgrestd
$ CARGO_TARGET_AARCH64_POSTGRES_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc STD_TARGET="aarch64-postgres-linux-gnu" ./run install
```

And you'll end up with this directory:  `~/.rustup/toolchains/1.65.0-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-postgres-linux-gnu`

Getting plrust to use that isn't working out yet, tho:

```sql
$ PLRUST_TARGET="x86_64-postgres-linux-gnu" \
CARGO_TARGET_AARCH64_POSTGRES_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc \
cargo pgx run pg15

psql (15.1)
Type "help" for help.

[v15.1][233250] plrust=# create or replace function one_rust() returns int language plrust as $$Some(1)$$;
WARNING:  target=x86_64-postgres-linux-gnu // compiles the x86_64 postgrestd target just fine
WARNING:  target=aarch64-postgres-linux-gnu // but bombs on the aarch64 version
ERROR:  
   0: `cargo build` failed

Location:
   /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/convert/mod.rs:552

`cargo build` stderr:
   error: failed to run `rustc` to learn about target-specific information

   Caused by:
     process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -Clink-args=-Wl,-undefined,dynamic_lookup --target aarch64-postgres-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)
     --- stderr
     error: Error loading target specification: Could not find specification for target "aarch64-postgres-linux-gnu". Run `rustc --print target-list` for a list of built-in targets
```

**Comment by eeeebbbbrrrr** [comment]
I think we've long since settled the issues discussed here.
