### ISSUE TITLE
pgx::memcxt safety / crash

### ISSUE THREAD

**Issue by JohnHVancouver** [tcdi/plrust#169]
We offer [memcxt](https://github.com/tcdi/plrust/blob/main/trusted-pgx/src/lib.rs#L38) manipulation as part of the trusted-pgx. 

I think we should remove it for the since it's hard to reason about correctness and safety when interacting with other libraries/extensions that could be relying on storing information in memory contexts while allowing "regular" users to manipulate them through PL/Rust. For instance, if we allow users to change memory [contexts back-and-forth](https://docs.rs/pgx/latest/pgx/memcxt/enum.PgMemoryContexts.html#method.set_as_current) I'm guessing we'll break some correctness guarantees eventually of extensions

I'm also not sure what a good use-case would be for it currently (although I'm probably missing something obvious).

Here's a function (which is on an outdated version of PL/Rust) allows a user to crash the database, leading to a seg fault.

```
CREATE OR REPLACE FUNCTION reset_top_memcxt() RETURNS TEXT 
IMMUTABLE STRICT
LANGUAGE PLRUST AS
$$
    use pgx::PgMemoryContexts::TopMemoryContext;

    TopMemoryContext.switch_to(|context| {
        // try resetting the mem_ctxt
        context.reset();
    });
    
    Some("reset".to_string())
$$;

postgres=> select reset_top_memcxt();
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Failed.
```

**Comment by workingjubilee** [comment]
Many recent changes have been done to alter how memory contexts behave. Does this with a recent version of plrust, using the 0.7.0-beta.1 pgx?

**Comment by eeeebbbbrrrr** [comment]
It can't be with 0.7.0-beta.1.  Both of those functions are unsafe now.  The above won't even compile with 070b1.

We expose PgMemoryContexts as some bits of pgx' generated code for #[pg_extern]/#[pg_trigger] use it.  Agreed it's not something users should use, which is why we made it all unsafe.

**Comment by JohnHVancouver** [comment]
Ah I should really read the latest-docs/try it out on latest. It does look like it's fixed in the latest pgx

**Comment by workingjubilee** [comment]
Feel free to reopen this if you can prove us wrong! Until then: no repro.
