### ISSUE TITLE
Update CI to use configured pgx version

### ISSUE THREAD

**Issue by eeeebbbbrrrr** [tcdi/plrust#180]
Right now, plrust's CI installs `cargo-pgx` from pgx' git repo, off its develop branch.

Instead, CI should peek inside `plrust/Cargo.toml` and pluck out the pgx version we're using, and simply execute `cargo install cargo-pgx --version $TheVersionFromCargoToml`.

Assuming CI's existing caching features do what they claim, this will allow subsequent CI runs that all use the same pgx version to skip installing cargo-pgx again, possibly saving ~4 minutes per job.

**Comment by BradyBonnette** [comment]
Yeah good idea. As mentioned in discord, I am fairly certain installing `cargo-pgx` from the develop branch was a relic of the past. Now that things are solidifying a bit, we should do this.

**Comment by eeeebbbbrrrr** [comment]
Right now we run `cargo install cargo-pgx ... --force`.  We don't want `--force` anymore if we're going to expect `cargo install` to skip installing the same version.

**Comment by BradyBonnette** [comment]
Got it.

**Comment by BradyBonnette** [comment]
@eeeebbbbrrrr #182 has been merged in, so this issue can be closed
