### ISSUE TITLE
pg_dump / pg_restore does not work

### ISSUE THREAD

**Issue by JohnHVancouver** [tcdi/plrust#204]
When we pg_dump a PL/Rust function the prosrc is a json.
We don't currently parse the json to recompile if a user has created it as one, it just errors out.

I think we need to do something similar to:

https://github.com/tcdi/plrust/blob/8cd37583559449db694b52b442b9ad80fe92a09b/plrust/src/prosrc.rs#L105-L112

and add it here when parsing?

https://github.com/tcdi/plrust/blob/main/plrust/src/user_crate/mod.rs#L295-L300

Check if code_and_deps can be converted into a ProSrcEntry. If so grab the ProSrcEntry.src otherwise assume not json and continue?

------

For reference I created a PL/Rust function and pg_dump the database

```
pg_dump -d plrust -h localhost -f plrust.sql
psql -f plrust.sql -d restore -h localhost
...
psql:plrust.sql:61: ERROR:  
   0: Parsing `[code]` block: expected one of: `for`, parentheses, `fn`, `unsafe`, `extern`, identifier, `::`, `<`, square brackets, `*`, `&`, `!`, `impl`, `_`, lifetime

Location:
   plrust/src/user_crate/mod.rs:277
```

**Comment by workingjubilee** [comment]
Uhm. Hm. Can you give a sample of the JSON that is expected, here?

**Comment by workingjubilee** [comment]
...Oh wait, of course. It's the one we store!

**Comment by eeeebbbbrrrr** [comment]
Sounds like something is bugged but the intent is that on a restore (create or replace that provides the json) we ignore everything except the “src” property and just do our full compile process.
