### ISSUE TITLE
Trigger support: Rename `current` to `old`

### ISSUE THREAD

**Issue by rustprooflabs** [tcdi/plrust#209]
# Details

The variable in a trigger function to reference an existing row's data is named `current` via pgx.  Can the `current` variable be renamed to `old` to be inline with existing trigger functions (e.g. [plpgsql](https://www.postgresql.org/docs/current/plpgsql-trigger.html))?  I am referencing pgx under  [trigger_support/pg_trigger_safe.rs](https://github.com/tcdi/pgx/blob/v0.7.1/pgx/src/trigger_support/pg_trigger_safe.rs#L8-L9).  The new row's data is in `new` as expected.

A current trigger function from [plrust/src/tests.rs](https://github.com/tcdi/plrust/blob/e604c2b5372337d12d7af0e8bf58c3bdbbcf14b5/plrust/src/tests.rs#L342-L354) referencing `current`:

```sql
CREATE FUNCTION pet_trigger() RETURNS trigger AS $$
    let current = trigger.current().unwrap();
    let mut current = current.into_owned();
    let field = "scritches";
    match current.get_by_name::<i32>(field).unwrap() {
        Some(val) => current.set_by_name(field, val + 1).unwrap(),
        None => (),
    }
    Ok(current)
$$ LANGUAGE plrust;
```

With the renaming this would change to:

```sql
CREATE FUNCTION pet_trigger() RETURNS trigger AS $$
    let old = trigger.old().unwrap();
    let mut old = old.into_owned();
    let field = "scritches";
    match old.get_by_name::<i32>(field).unwrap() {
        Some(val) => old.set_by_name(field, val + 1).unwrap(),
        None => (),
    }
    Ok(old)
$$ LANGUAGE plrust;
```

**Comment by eeeebbbbrrrr** [comment]
I'll be putting up a PR over on pgx in a bit to resolve this.  It allows your expected function to work.  And I've tidied it up here to use the `?` where Results are returned:

```postgres
CREATE FUNCTION pet_trigger() RETURNS trigger AS $$
    let old = trigger.old().unwrap();
    let mut old = old.into_owned();
    let field = "scritches";
    match old.get_by_name::<i32>(field)? {
        Some(val) => old.set_by_name(field, val + 1)?,
        None => (),
    }
    Ok(old)
$$ LANGUAGE plrust;
```
