### ISSUE TITLE
Can't disable linting in plrust / other lint configurations

### ISSUE THREAD

**Issue by JohnHVancouver** [tcdi/plrust#218]
There seems to be two potential issues here:
1. No way to specify no lints
2. No way to check if a lint is valid

`plrust.compile_lints` and `plrust.required_lints` are currently string gucs and there isn't a way to disable them if desired. 

For 1) if the parameters are set to an empty string `''`  we get:

```
ERROR:  Ident is not allowed to be empty; use Option<Ident>
```

For 2) if we set the guc to a random string it'll error with something like:

```
   error: unknown lint: `batcat`
     --> src/lib.rs:22:15
      |
   22 |     #![forbid(batcat)]
      |               ^^^^^^
      |
   note: the lint level is defined here
     --> src/lib.rs:20:8
      |
   20 | #[deny(unknown_lints)]
      |        ^^^^^^^^^^^^^
```

2) doesn't seem like the worst thing in the world. 

Not sure if we should introduce a magic string of "None" that if that's the only "lint" we don't bother including  `#lints` 
https://github.com/tcdi/plrust/blob/main/plrust/src/user_crate/crating.rs#L319

**Comment by eeeebbbbrrrr** [comment]
1 is a bug. Setting the GUC to the empty string should turn them off. 

2 is a thing we want. It makes no sent to configure a lint you think is protecting you from something when in fact it doesn’t even exist.

**Comment by workingjubilee** [comment]
Yes, we should reject invalid configurations no later than runtime.

Right now, the answer to "is a lint valid?" is going to be answered by attempting to compile something. That's a bit late, but it's really the only source of truth we can be sure of, so while we could try to move that information up to configuration time, it would not necessarily be aligned with the actual source of truth and so we should be cautious about trying to be overly helpful in a way that may later prove to be a lie.

I should note that you are allowed to use `#![allow(unknown_lints)]` _inside_ the function, but that's not the same as the administrator configuration. It makes no sense to allow invalid administrator configurations, it is fine to allow users to try to manipulate lints that we don't actually recognize and have no stake in. They can't allow, warn, or deny any lints we have already forbidden, however.

We could adjust things to be even more permissive in terms of the function code itself, but we still aren't going to allow invalid administrator configurations.
