### ISSUE TITLE
Improve error - Create function with anonymous variables

### ISSUE THREAD

**Issue by rustprooflabs** [tcdi/plrust#255]
# Details

PL/Rust functions are not expected to support anonymous input parameters like other languages do, e.g `$1`. The current error message when this is attempted is not helpful to the end user.

```sql
CREATE FUNCTION plrust.strlen(TEXT)
    RETURNS BIGINT
    LANGUAGE plrust STRICT
AS $$
    Ok(Some(arg0.len() as i64))
$$;
```

Returns

```
ERROR:  assertion failed: `(left == right)`
  left: `0`,
 right: `1`
DETAIL:  
```

It would be great to have a more informative error message in this case.

**Comment by eeeebbbbrrrr** [comment]
@rustprooflabs, got a PR up for this at https://github.com/tcdi/plrust/pull/258

The rules are:

- error if the argument is unnamed
- error if the argument name isn't also a valid Rust identifier

I'll let you update the docs for this.  The docs probably need a section about the rules and regulations such as, now, argument naming, argument types (`Option<T>` or `T` depending on STRICT), return types (`Result<Option<T>>`), and maybe other things I haven't thought of.
