### ISSUE TITLE
RFC: Remote Compilation

### ISSUE THREAD

**Issue by Hoverbear** [tcdi/plrust#27]
Not everyone is happy about having a development toolchain on their database machine.

PL/Rust should support some sort of remote compilation facility. 

* PL/Rust should have some GUC defining between `local` or `remote` builds, and not require any development tools locally if `remote` is specified.
* When `remote` is specified, PL/Rust should provide GUC settings to configure the remote.

## Open Questions

What does that remote compilation process look like? Do we send just the user's string of Rust code, or does PL/Rust generate the entire crate and ship it off?

Could we utilize well known environments like AWS Lambda, Cloudflare workers, or Fastly's compute edge to create these artifacts?

What does this API look like?

**Comment by Hoverbear** [comment]
#48 gets us to a point where we could add a state of `StateRemotelyBuilding` which can be reached via `StateGenerated` and can transition to `StateBuilt`.

**Comment by johnrballard** [comment]
This is no longer required.
