### ISSUE TITLE
build script requires USER environment variable to be present & valid

### ISSUE THREAD

**Issue by yrashk** [tcdi/plrust#278]
However, this is not always the case:

```
#40 462.6 thread 'tests::tests::pg_named_unnamed_args' panicked at 'USER environment var is unset or invalid UTF-8', /var/lib/postgresql/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-tests-0.7.4/src/framework.rs:622:29
```

```
$ docker run -ti --rm debian
root@d9162bd521d1:/# echo $USER

root@d9162bd521d1:/#
exit
$ docker run -ti --rm postgres:15.2-bullseye bash
root@66535841306b:/# echo $USER

root@66535841306b:/#
```

It should be either documented for those installing the extension or perhaps simply set in the build script if not present (something like `USER=$(id -un)`

**Comment by workingjubilee** [comment]
That's because the script implicitly runs the tests as well, and they should probably stop doing so now that it isn't necessarily a part of our test workflow. Though, `$USER` not being set is pretty strange, as an environment, because it's supposed to be done on login.

**Comment by yrashk** [comment]
There's no login in the container building.

**Comment by eeeebbbbrrrr** [comment]
As @workingjubilee pointed out the build script no longer runs the test suite, so I believe this is fixed in `develop`.  If it turns out it's not when v1.1.0 is released later this week we can take another look.
