### ISSUE TITLE
rust version error

### ISSUE THREAD

**Issue by FreeGIS** [tcdi/plrust#290]
```
 0: Mismatched rust versions: `cargo-pgx` was built with Rust `1.68`, but Rust `1.67` is currently in use.
```
My rust is version 1.68, but plrust requires 1.67. Can I make plrust consistent with the installed rust in the system?

**Comment by FreeGIS** [comment]
The version info:
```
[root@VM-0-14-centos plrust-1.0.0]# rustc -V
rustc 1.67.1 (d5a82bbd2 2023-02-07)
[root@VM-0-14-centos plrust-1.0.0]# cd /opt
[root@VM-0-14-centos opt]# rustc -V
rustc 1.68.2 (9eb3afe9e 2023-03-27)

```

**Comment by thomcc** [comment]
Unfortunately no, even if you got past that error, PL/Rust uses a custom fork of the standard library (<https://github.com/tcdi/postgrestd>) and a custom Rustc compiler driver (<https://github.com/tcdi/plrust/tree/main/plrustc>). So it has a hard dependency on 1.67.1.

**Comment by FreeGIS** [comment]
@thomcc Thanks.I will keep an eye on it because I want to use my own installed PostgreSQL and rust, but plrust and pgx prefer to have some built-in software, but that's not what we expected. We hope to develop stored procedures and extensions for the existing PostgreSQL on this machine

**Comment by thomcc** [comment]
You should be able to use your own PostgreSQL, just not your own Rust. I don't think we have plans to change that (and am not sure how we would).

**Comment by eeeebbbbrrrr** [comment]
PL/Rust is compatible with Postgres v13, 14, 15.  

Building PL/Rust, and then the resulting `LANGUAGE plrust` functions, do, however, require the Rust 1.67.1 toolchain.

As time goes on we'll likely update toolchain requirements, but we'll always be some bit behind as we have our own fork of the standard library (postgrestd).
