### ISSUE TITLE
Stripping release artifacts

### ISSUE THREAD

**Issue by BradyBonnette** [tcdi/plrust#305]
An issue was raised upon looking at the PL/Rust Debian package file sizes as a result of the release process -- the file sizes looked fairly big.

The question becomes:  Should we strip anything in `release` mode for PL/Rust? If so, what should be stripped and how should it be stripped? 

One suggestion was to update the profile for the PL/Rust project, as in: https://doc.rust-lang.org/cargo/reference/profiles.html#strip

Another suggestion was to potentially strip the user-created functions, but there was concerned this could break dynamic loading.

**Comment by eeeebbbbrrrr** [comment]
This is done now.
