### ISSUE TITLE
RFC:  Need support for `... RETURNS TABLE (...)`

### ISSUE THREAD

**Issue by eeeebbbbrrrr** [tcdi/plrust#36]
We need to support Postgres' SRF api.

**Comment by Hoverbear** [comment]
SETOF is already supported, TABLE needs work!

**Comment by rustprooflabs** [comment]
+1 for supporting this.  Using `RETURNS TABLE` lets the data types be coded into the function definition.  Using `RETURNS SETOF` often involves creating custom types.  Many of these types would only be used for a single `SETOF` function.

**Comment by eeeebbbbrrrr** [comment]
This got merged in PR #326

**Comment by seanlinsley** [comment]
Looks like the docs need updating https://github.com/tcdi/plrust/blob/main/doc/src/spi.md#complex-return-types
