### ISSUE TITLE
fix `plrust/build` to dynamically determine pgrx version

### ISSUE THREAD

**Issue by eeeebbbbrrrr** [tcdi/plrust#377]
https://github.com/tcdi/plrust/blob/9f0f459899b8982623ae2b7b7ddbfcf394f87cb8/plrust/build#L56

That line needs to not hardcode the pgrx version.  The ideal solution is that it can figure it out from the sibling Cargo.toml file.

**Comment by BradyBonnette** [comment]
Closing as a result of https://github.com/tcdi/plrust/pull/381 getting merged into `develop`
