### ISSUE TITLE
[RFC] Separating PL/Rust work_dir 

### ISSUE THREAD

**Issue by JohnHVancouver** [tcdi/plrust#86]
Hello,

Currently in the `plrust.work_dir = 'scratch'` we put everything in there.

This makes it difficult to have additional restrictions in place for these directories as it's hard to distinguish between a `plrust_foo.so` vs `plrust_fn_oid_49152` (the cargo project) vs the `target` directory. 

Similar to wanting to dump temporary code/artifacts in `/tmp` and the final artifact in `/usr/bin` we're thinking of one of the following changes:

1. Keep one configuration parameter `plrust.work_dir = 'scratch'` and create `~/scratch/compile` where `compile` has something like `~/scratch/compile/target` and `~/scratch/compile/package`. While the final `plrust.so` would live in `~/scratch/artifacts`

2. Move to two configuration parameters `plrust.work_dir` and `plrust.artifact_dir` where work_dir would have similar semantics today, and artifact_dir just contains the final artifact.

**Comment by workingjubilee** [comment]
I have no idea what the difference between `~/scratch/compile/target` and `~/scratch/compile/package` would be, honestly.

**Comment by jbrindle** [comment]
target could theoretically be pre-cached and read only but that isn't as important as separating the artifact (final binaries) from the compilation environment.
