### ISSUE TITLE
plrust should clean up artifacts

### ISSUE THREAD

**Issue by BradyBonnette** [tcdi/plrust#99]
In a conversation with @eeeebbbbrrrr in talking about https://github.com/tcdi/plrust/issues/81 we discovered that there are some opportunities to have plrust clean up artifacts at various points

- [ ] Adding callbacks on transaction abort and pre-commit to recursively delete crate directory
- [ ] Adding callbacks for drop schema and drop function
- [ ] Discuss target dir (e.g. shared compiled dependencies `<root level scratch directory>/target`)
- [ ] Discuss using database directory for shared library storage (e.g. postgres' `data_directory` GUC) so that any built artifacts can also be dropped in the event of a `drop database` call

**Comment by eeeebbbbrrrr** [comment]
We no longer leave anything on disk (outside of the `target/` directory) after a successful compile.
